port: auto
baud-rate: 9600
apps:
    - master
    - opera.exe
    - discord.exe
    - group:
          - spotify.exe
          - AMPLibraryAgent.exe
    - game:
          - geometrydash.exe
          - albion-online.exe
          - rustclient.exe
          - robloxplayerbeta.exe
          - cs2.exe
